name: code_magic_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.5
  keyboard_dismisser: ^3.0.0
  date_format: ^2.0.7
  fluttertoast: ^8.1.2
  form_field_validator: ^1.1.0
  mask_text_input_formatter: ^2.4.0
  equatable: ^2.0.5
  path_provider: ^2.0.11
  connectivity_plus: ^3.0.2
  logger: ^1.1.0
  dio: ^4.0.6
  json_annotation: ^4.7.0
  socket_io_client: ^2.0.0
  meta: ^1.8.0
  cached_network_image: ^3.2.3
  flutter_dotenv: ^5.0.2
  path: ^1.8.0
  http: ^0.13.5
  permission_handler: ^10.2.0
  image_picker: ^0.8.6
  file_picker: ^5.2.4
  get: ^4.6.5
  get_storage: ^2.0.3
  open_filex: ^4.3.2
  url_launcher: ^6.1.7
  flutter_linkify: ^5.0.2
  dots_indicator: ^2.1.0
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^9.1.5
  enum_to_string: ^2.0.1
  dotted_border: ^2.0.0+3
  geolocator: ^9.0.2
  flutter_smartlook: ^4.0.6
  expandable: ^5.0.1
  intl: ^0.18.0
  flutter_inappwebview: ^5.7.2+3
  collection: ^1.15.0
  google_directions_api: ^0.9.1
  horizontal_blocked_scroll_physics: ^4.0.1
  location: ^4.4.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.1.6
  device_info_plus: ^8.0.0
  package_info_plus: ^3.0.2
  lottie: ^2.1.0
  cropperx: ^1.1.1
  uuid: ^3.0.7

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  build_runner: ^2.0.3
  json_serializable: ^6.1.3

flutter: 
  uses-material-design: true

